const stats = [
  {
    approaches: 2,
    date: "6/13/2019",
    followUpDates: 0,
    performanceRating: 1,
    phoneNumbers: 1,
    sameDayLays: 0,
    weekday: "Thursday",
  },
  {
    approaches: 16,
    date: "6/14/2019",
    followUpDates: 0,
    performanceRating: 3,
    phoneNumbers: 3,
    sameDayLays: 0,
    weekday: "Friday",
  },
  {
    approaches: 6,
    date: "6/15/2019",
    followUpDates: 0,
    performanceRating: 2,
    phoneNumbers: 1,
    sameDayLays: 0,
    weekday: "Saturday",
  },
  {
    approaches: 12,
    date: "6/19/2019",
    followUpDates: 0,
    performanceRating: 1,
    phoneNumbers: 1,
    sameDayLays: 0,
    weekday: "Wednesday",
  },
  {
    approaches: 12,
    date: "6/21/2019",
    followUpDates: null,
    performanceRating: 2,
    phoneNumbers: 1,
    weekday: "Friday",
  },
    approaches: 6,
    date: "6/21/2019",
    followUpDates: null,
    performanceRating: 2,
    phoneNumbers: 2,
    weekday: "Saturday",
  },
];

export default stats;
