module.exports = [
  {
    approaches: 2,
    date: "6/13/2019",
    followUpDates: 0,
	game: 'night',
    performanceRating: 1,
    phoneNumbers: 1,
    sameDayLays: 0,
    weekday: "Thursday",
  },
  {
    approaches: 16,
    date: "6/14/2019",
    followUpDates: 0,
	game: 'night',
    performanceRating: 3,
    phoneNumbers: 3,
    sameDayLays: 0,
    weekday: "Friday",
  },
  {
    approaches: 6,
    date: "6/15/2019",
    followUpDates: 0,
	game: 'night',
    performanceRating: 2,
    phoneNumbers: 1,
    sameDayLays: 0,
    weekday: "Saturday",
  },
  {
    approaches: 12,
    date: "6/19/2019",
    followUpDates: 0,
	game: 'day',
    performanceRating: 1,
    phoneNumbers: 1,
    sameDayLays: 0,
    weekday: "Wednesday",
  },
  {
    approaches: 12,
    date: "6/21/2019",
    followUpDates: 1,
	game: 'night',
    performanceRating: 2,
    phoneNumbers: 1,
    weekday: "Friday",
  },
  {
    approaches: 6,
    date: "6/22/2019",
    followUpDates: 0,
	game: 'night',
    performanceRating: 2,
    phoneNumbers: 2,
    weekday: "Saturday",
  },
  {
    approaches: 8,
    date: "7/13/2019",
    followUpDates: 0,
	game: 'night',
    performanceRating: 1,
    phoneNumbers: 0,
    weekday: "Saturday",
  },
  {
    approaches: 17,
    date: "7/19/2019",
    followUpDates: 1,
	game: 'day',
    instaDate: 1,
    performanceRating: 2,
    phoneNumbers: 3,
    weekday: "Friday",
  },
  {
    approaches: 9,
    date: "7/20/2019",
    followUpDates: 0,
	game: 'night',
    instaDate: 0,
    performanceRating: 1,
    phoneNumbers: 1,
    weekday: "Saturday",
  },
  {
    approaches: 14,
    date: "7/27/2019",
    followUpDates: 0,
	game: 'day',
    instaDate: 0,
    performanceRating: 1,
    phoneNumbers: 0,
    weekday: "Saturday",
  },
  {
    approaches: 6,
    date: "8/1/2019",
    followUpDates: 0,
	game: 'night',
    instaDate: 0,
    performanceRating: 2,
    phoneNumbers: 1,
	sameDayLays: 1,
    weekday: "Thursday",
  },
  {
    approaches: 3,
    date: "8/3/2019",
    followUpDates: 0,
	game: 'night',
    instaDate: 0,
    performanceRating: 1,
    phoneNumbers: 0,
	sameDayLays: 0,
    weekday: "Saturday",
  },
  {
    approaches: 9,
    date: "8/8/2019",
    followUpDates: 0,
	game: 'night',
    instaDate: 0,
    performanceRating: 1,
    phoneNumbers: 0,
	sameDayLays: 0,
	solo: true,
    weekday: "Friday",
  },
];
